spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5433/flashmind}
    username: ${DB_USERNAME:flashmind}
    password: ${DB_PASSWORD:flashmind}
  jpa:
    show-sql: true

flashmind:
  auth:
    allow-dev-login-bypass: true
  social:
    skip-id-token-validation: true
  generation:
    ai-provider: mock
